var responsiveHelper_dt_meetings = undefined;

var breakpointDefinitiondt_meetings = {
tablet : 1024,
phone : 480
};


$('#dt_meetings').dataTable({

// Tabletools options:
//   https://datatables.net/extensions/tabletools/button_options             stateSave: true,

"pageLength": 10,
"order": [[ 2, "asc" ]],
"columnDefs": [
{"targets": [5],"orderable": false},
],
"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
"t"+
"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
"oTableTools": {
"aButtons": [
"copy",
"csv",
"xls",
{
"sExtends": "pdf",
"sTitle": "Tracker_PDF",
"sPdfMessage": "Tracker PDF Export",
"sPdfSize": "letter"
},
{
"sExtends": "print",
"sMessage": "Generated by Tracker <i>(press Esc to close)</i>"
}
],
"sSwfPath": "{{ URL::asset('js/plugin/datatables/swf/copy_csv_xls_pdf.swf') }}"
},
"autoWidth" : true,
"preDrawCallback" : function() {
// Initialize the responsive datatables helper once.
if (!responsiveHelper_dt_meetings) {
responsiveHelper_dt_meetings = new ResponsiveDatatablesHelper($('#dt_meetings'), breakpointDefinitiondt_meetings);
}
},
"rowCallback" : function(nRow) {
responsiveHelper_dt_meetings.createExpandIcon(nRow);
},
});