{{\tracker\Helpers\Session::SetRedirect(action('MeetingController@index', [$subjecttype, $subjectid]))}}

@extends('layouts.main')
@inject('formater', 'tracker\Helpers\HtmlFormating')

@section('heading'){{$title}} @endsection

@include('partials.breadcrumb')

@section('content')

    <div class="jarviswidget jarviswidget-color-darken" id="wid-id-meetings" data-widget-editbutton="false" data-widget-deletebutton="false">

        <header>
            <span class="widget-icon"> <i class="fa fa-calendar"></i> </span>
            <h2>Meetings</h2>

        </header>

        <!-- widget div-->
        <div>

            <!-- widget content -->
            <div class="widget-body">

                <table id="dt_meetings" class="table table-striped table-bordered table-hover" width="100%">
                    <thead>
                    <tr>

                        <th  data-class="expand">ID</th>
                        <th>Title</th>
                        <th data-hide="phone,tablet">Start</th>
                        <th data-hide="phone,tablet">Duration</th>
                        <th data-hide="always">Description</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($meetings as $meeting)

                        <tr>
                            <td >{{$meeting->id}}</td>
                            <td>{{$meeting['title']}}</td>

                            @if($meeting->all_day_event)
                                <td class="text-nowrap">{{$meeting->start_date->format('d M Y')}}</td>
                                <td>All Day Event</td>
                            @else
                                <td class="text-nowrap">{{$meeting->start_date->format('d M Y g:i a')}}</td>
                                <td>{{$meeting->duration}} hours</td>
                            @endif


                            <td>{{$meeting['description']}}</td>
                            <td class="text-nowrap">
                                <a href="{{ URL::asset('meetings/') }}/{{$meeting['id']}}" class="btn btn-default btn-sm" rel="tooltip" data-placement="top" data-original-title="View"><i class="fa fa-folder"></i></a>
                                <a href="{{action('MeetingController@edit', [$meeting->id])}}" class="btn btn-default btn-sm" rel="tooltip" data-placement="top" data-original-title="Edit"><i class="fa fa-pencil"></i></a>
                                @if( auth()->check() && auth()->user()->isAdmin() )
                                    <a class="btn btn-default btn-sm"
                                       rel="tooltip" data-placement="top" data-original-title="Delete"
                                       href="{{action('MeetingController@destroy', $meeting->id)}}"
                                       data-delete=""
                                       data-title="Delete Meeting"
                                       data-message="Are you sure you want to delete this meeting?"
                                       data-button-text="Confirm Delete"><i style="color: black" class="fa fa-trash-o"></i> </a>
                                @endif
                            </td>


                        </tr>

                    @endforeach

                    </tbody>
                </table>

                <div class="widget-footer">
                    <div class="pull-left">
                        <a href="{{action('MeetingController@create', [$subjecttype, $subjectid])}}" class="btn btn-primary btn-sm">Add new Meeting</a>

                    </div>

                </div>

            </div>
        </div>
    </div>


@endsection

@section('readyfunction')

    var responsiveHelper_dt_meetings = undefined;

    var breakpointDefinitiondt_meetings = {
    tablet : 1024,
    phone : 480
    };


    $('#dt_meetings').dataTable({

    // Tabletools options:
    //   https://datatables.net/extensions/tabletools/button_options
    stateSave: true,

    "pageLength": 25,
    "order": [[ 2, "asc" ]],
    "columnDefs": [
        {"targets": [5],"orderable": false},
    ],
    "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
    "t"+
    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
    "oTableTools": {
    "aButtons": [
    "copy",
    "csv",
    "xls",
    {
    "sExtends": "pdf",
    "sTitle": "Tracker_PDF",
    "sPdfMessage": "Tracker PDF Export",
    "sPdfSize": "letter"
    },
    {
    "sExtends": "print",
    "sMessage": "Generated by Tracker <i>(press Esc to close)</i>"
    }
    ],
    "sSwfPath": "{{ URL::asset('js/plugin/datatables/swf/copy_csv_xls_pdf.swf') }}"
    },
    "autoWidth" : true,
    "preDrawCallback" : function() {
    // Initialize the responsive datatables helper once.
    if (!responsiveHelper_dt_meetings) {
    responsiveHelper_dt_meetings = new ResponsiveDatatablesHelper($('#dt_meetings'), breakpointDefinitiondt_meetings);
    }
    },
    "rowCallback" : function(nRow) {
    responsiveHelper_dt_meetings.createExpandIcon(nRow);
    },
    });

@endsection