var responsiveHelper_dt_userrisks = undefined;

var breakpointDefinitiondt_userrisks = {
tablet : 1024,
phone : 480
};


$('#dt_userrisks').dataTable({
stateSave: true,
"createdRow": function ( row, data, index )
{
if (beforenow( data[8] )) {
$('td', row).eq(8).addClass('text-danger').css('font-weight', 'bold');
}
else if (next5days( data[8] )) {
$('td', row).eq(8).addClass('text-warning').css('font-weight', 'bold');
}
},
"pageLength": 10,
"order": [[ 8, "asc" ]],
"columnDefs": [
{"targets": [10],"orderable": false},
],
"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
"t"+
"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
"oTableTools": {
"aButtons": [
"copy",
"csv",
"xls",
{
"sExtends": "pdf",
"sTitle": "Tracker_PDF",
"sPdfMessage": "Tracker PDF Export",
"sPdfSize": "letter"
},
{
"sExtends": "print",
"sMessage": "Generated by Tracker <i>(press Esc to close)</i>"
}
],
"sSwfPath": "{{ URL::asset('js/plugin/datatables/swf/copy_csv_xls_pdf.swf') }}"
},
"autoWidth" : true,
"preDrawCallback" : function() {
// Initialize the responsive datatables helper once.
if (!responsiveHelper_dt_userrisks) {
responsiveHelper_dt_userrisks = new ResponsiveDatatablesHelper($('#dt_userrisks'), breakpointDefinitiondt_userrisks);
}
},
"rowCallback" : function(nRow) {
responsiveHelper_dt_userrisks.createExpandIcon(nRow);
},
});

var table = $('#dt_userrisks').DataTable();

var filteredData = table
.column( 5 )
.search('Open');

table.draw();