var responsiveHelper_dt_usertasks = undefined;

var breakpointDefinitiondt_usertasks = {
tablet : 1024,
phone : 480
};


$('#dt_usertasks').dataTable({

stateSave: true,
"pageLength": 10,
"order": [[ 0, "asc" ]],
"columnDefs": [
{"targets": [8],"orderable": false},
],
"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
"t"+
"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
"oTableTools": {
"aButtons": [
"copy",
"csv",
"xls",
{
"sExtends": "pdf",
"sTitle": "Tracker_PDF",
"sPdfMessage": "Tracker PDF Export",
"sPdfSize": "letter"
},
{
"sExtends": "print",
"sMessage": "Generated by Tracker <i>(press Esc to close)</i>"
}
],
"sSwfPath": "{{ URL::asset('js/plugin/datatables/swf/copy_csv_xls_pdf.swf') }}"
},
"autoWidth" : true,
"preDrawCallback" : function() {
// Initialize the responsive datatables helper once.
if (!responsiveHelper_dt_usertasks) {
responsiveHelper_dt_usertasks = new ResponsiveDatatablesHelper($('#dt_usertasks'), breakpointDefinitiondt_usertasks);
}
},
"rowCallback" : function(nRow) {
responsiveHelper_dt_usertasks.createExpandIcon(nRow);
},
});

var table = $('#dt_usertasks').DataTable();

var filteredData = table
.column( 4 )
.search('Open');

table.draw();