
$('#dt_comments').dataTable({

// Tabletools options:
//   https://datatables.net/extensions/tabletools/button_options

"pageLength": 10,
"order": [[ 0, "desc" ]],
"columnDefs": [
{"targets": [3],"orderable": false},
],
"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
"t"+
"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
"oTableTools": {
"aButtons": [
"copy",
"csv",
"xls",
{
"sExtends": "pdf",
"sTitle": "Tracker_PDF",
"sPdfMessage": "Tracker PDF Export",
"sPdfSize": "letter"
},
{
"sExtends": "print",
"sMessage": "Generated by Tracker <i>(press Esc to close)</i>"
}
],
"sSwfPath": "{{ URL::asset('js/plugin/datatables/swf/copy_csv_xls_pdf.swf') }}"
},
"autoWidth" : true

});